import type { Metadata } from "next";
import "./globals.css";
import { Noto_Sans_Thai  } from 'next/font/google'

const notoSansThai = Noto_Sans_Thai({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['thai', 'latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="th">
      <body className={notoSansThai.className}>  {/* หรือ ibmPlexSansThai.className */}
        {children}
      </body>
    </html>
  )
}
